---
 - name: Create an iam user
   iam:
    iam_type: user
    name: "{{ item }}"
    state: present
   register: username
   with_items: "{{ users }}"
    
 - debug:
     msg: "{{ username }}"


 - name: Apply policy to the created user
   iam_policy:
    iam_type: user
    iam_name: "{{ item }}"
    policy_name: TestPolicy
    #policy_document: files/testpolicy.json.j2
    policy_json: "{{ lookup( 'file', 'files/TestPolicy.json') }}"
    state: present
   register: policy
   with_items: "{{ users }}"