---
- hosts: localhost
  connection: local

- name: Get the Disk Names having  from the VMS having tag snapshot==yes
  command: az vm list -g "{{ resource_group }}" -o tsv
  register: command_output
- debug: msg="{{command_output.stdout_lines}}"