---
 - name: Create an iam user
   iam:
    iam_type: user
    name: "aditya"
    state: present
   register: username
    
 - debug:
     msg: "{{ username }}"


 - name: Apply policy to the created user
   iam_policy:
    iam_type: user
    iam_name: "aditya"
    policy_name: TestPolicy
    #policy_document: files/testpolicy.json.j2
    policy_json: "{{ lookup( 'file', 'testpolicy.json') }}"
    state: present
   #register: username

 #- debug:
  #   msg: The user created is {{ username }}