---
 - name: Create an iam user
   iam:
    iam_type: user
    name: "{{ user1 }}"
    state: present
   register: username
    
 - debug:
     msg: "{{ username }}"


 - name: Apply policy to the created user
   iam_policy:
    iam_type: user
    iam_name: "{{ user1 }}"
    policy_name: TestPolicy
    policy_document: files/testpolicy.json
    state: present
   #register: username

 #- debug:
  #   msg: The user created is {{ username }}