---
- name: Get the Disk Names having  from the VMS having tag snapshot==yes
  command: az vm list --query "[?tags.snapshot=='yes'].storageProfile.dataDisks[].name" -o json && az vm list --query "[?tags.snapshot=='yes'].storageProfile.osDisk[].name" -o json
  register: command1_output
- debug: msg="{{command_output.stdout_lines}}"

- debug: 
    msg: "{{ item }}"
  with_items: "{{ command_output.stdout_lines }}" 

- name: Create Snapshot of the listed disks
  command: az snapshot create -g OpsAutomator  -n "{{ '_'.join((item, extension)) }}" --source "{{ item }}"
  with_items: "{{ command_output.stdout_lines }}"