---
######################################################################################################################################################################################################################################################################################
# FINDING UNTAGGED SNAPSHOTS 
###################################################################################################################################################################################################################################################################################### 
- name: List out snapshots in a subscription with the Expiry tags mentioned
  shell: az snapshot list --query "[?tags.Expiry != values[]].[name,tags.Expiry,timeCreated]" -o tsv | sed -e 's/\t/,/g'
  register: ensured_snapshot_details
- debug: msg="{{ ensured_snapshot_details.stdout_lines }}"

- debug:
    msg: "{{ item }}"
  with_items: "{{ ensured_snapshot_details.stdout_lines }}"