---
######################################################################################################################################################################################################################################################################################
# FINDING Snapshots with the EXPIRY TAG and displaying the snapshot details
###################################################################################################################################################################################################################################################################################### 
- name: List out snapshots in a subscription with the Expiry tags mentioned
  shell: az snapshot list --query "[?tags.Expiry != values[]].[name, tags.Expiry, timeCreated]" -o json 
  #| sed -e 's/\t/,/g'
  register: ensured_snapshot_details
- debug: 
    msg: "{{ (ensured_snapshot_details['start']  - '%Y-%m-%d %H:%M:%S') }}"
    # - ('%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch))).days }}"
#- debug:
   # msg: "{{ item[2] }}"
  #with_items: "{{ ensured_snapshot_details.stdout_lines | join('\n') }}"

######################################################################################################################################################################################################################################################################################
# Get the Number of Days
###################################################################################################################################################################################################################################################################################### 
#- name: test
