---
######################################################################################################################################################################################################################################################################################
# FINDING Snapshots with the EXPIRY TAG and displaying the snapshot details
###################################################################################################################################################################################################################################################################################### 
- name: List out snapshots in a subscription with the Expiry tags mentioned
  shell: az snapshot list --query "[?tags.Expiry != values[]].[name, tags.Expiry, timeCreated]" -o json
  #| sed -e 's/\t/,/g'
  #[name, tags.Expiry, timeCreated]
  register: ensured_snapshot_details
- debug:    
    msg: "{{ ensured_snapshot_details['stdout_lines'][4] | to_datetime() }}"
    # | to_datetime('%Y-%m-%d %H:%M:%S.%f%z'))- ('%Y-%m-%d %H:%M:%S.%f%z' | to_datetime('%Y-%m-%d %H:%M:%S.%f%z'))).days }}"
    #(("2016-08-14 20:00:12" | to_datetime) - ("2015-12-25" | to_datetime('%Y-%m-%d'))).days  }}     
    #ensured_snapshot_details['start']
    #- '%Y-%m-%d %H:%M:%S' | to_datetime('%Y-%m-%d %H:%M:%S') }}"
    # - ('%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch))).days }}"
#- debug:
   # msg: "{{ item[2] }}"
  #with_items: "{{ ensured_snapshot_details.stdout_lines | join('\n') }}"

######################################################################################################################################################################################################################################################################################
# Get the Number of Days
###################################################################################################################################################################################################################################################################################### 
#- name: Get the snapshot age in number of days using python
  #script: files/calculateDays.py {{ item }} 
  #with_items: "{{ ensured_snapshot_details['start'] }}"
 # register: snapshot_age_in_days
#- debug:
    #msg: "{{ snapshot_age_in_days.stdout_lines }}"