---
######################################################################################################################################################################################################################################################################################
# FINDING UNTAGGED SNAPSHOTS 
###################################################################################################################################################################################################################################################################################### 
- name: List out Untagged snapshots in a subscription
  shell: az snapshot  list --query "[?not_null(tags.Expiry = '*')].[timeCreated, tags,]" -o tsv | sed -e 's/\t/,/g'
  register: ensured_snapshot_details
- debug: msg="{{ ensured_snapshot_details.stdout_lines }}"

- debug:
    msg: "{{ item }}"
  with_items: "{{ ensured_snapshot_details.stdout_lines }}"