---
######################################################################################################################################################################################################################################################################################
# Create file to store snapshot details fetched from shell script
###################################################################################################################################################################################################################################################################################### 
- name: Create a file to store the Snapshot List json output
  copy:
    dest: "/home/ansible/Azure_Old_Snapshot_List{{ '%Y-%m-%d' | strftime(ansible_date_time.epoch) }}.json"
    content: ""
    owner: ansible
    group: ansible
    mode: '0666'
  register: raw_report
- debug:
    msg: "{{ raw_report['dest'] }}"

######################################################################################################################################################################################################################################################################################
# Template AZ SNAPSHOT LIST shell script to target system
######################################################################################################################################################################################################################################################################################
#- name: Template Snapshot Listing Shell script on target system
  #template:
    #src: template/List_azure_snapshots.sh
    #dest: /home/ansible/az_snapshot_list{{ '%Y-%m-%d%H:%M:%S' | strftime(ansible_date_time.epoch) }}.sh
    #owner: ansible
    #group: ansible
    #mode: '0700'
######################################################################################################################################################################################################################################################################################
# Shell script to list azure snapshots with Expiry Tag
######################################################################################################################################################################################################################################################################################
- name: List Azure Snapshots having Expiry tag
  script: files/az_snapshot_list.sh "{{ item }}"
  with_items: "{{ raw_report['dest'] }}"
  register: report
- debug:
    msg: "{ report }"