---
######################################################################################################################################################################################################################################################################################
# Create file to store snapshot details fetched from shell script
###################################################################################################################################################################################################################################################################################### 
- name: Create a file to store the Snapshot List json output
  copy:
    dest: "/home/ansible/Azure_Old_Snapshot_List{{ '%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch) }}.json"
    content: ""
    owner: ansible
    group: ansible
    mode: '0744'
  register: json_file
- debug:
    msg: "{{ json_file['dest'] }}"

######################################################################################################################################################################################################################################################################################
# Template AZ SNAPSHOT LIST shell script to target system
######################################################################################################################################################################################################################################################################################
- name: Template Snapshot Listing Shell script on target system
  template:
    src: template/az_snapshot_list.sh
    dest: /home/ansible/az_snapshot_list.sh 
    owner: ansible
    group: ansible
    mode: '0770'
  register: shell_script
- debug:
    msg: "{{ shell_script }}"
######################################################################################################################################################################################################################################################################################
# Shell script to list azure snapshots with Expiry Tag
######################################################################################################################################################################################################################################################################################
- name: List Azure Snapshots having Expiry tag
  shell: /home/ansible/az_snapshot_list.sh > "{{ item }}"
  with_items: "{{ json_file['dest'] }}"
  register: report
- debug:
    msg: "{{ report }}"

######################################################################################################################################################################################################################################################################################
# Perform Operations on snapshot report using python to filter out snapshot details
######################################################################################################################################################################################################################################################################################
- name: Filter Out Snapshot Details
  script: files/operate.py "{{ json_file['dest'] }}"
  register: operate_results
#- debug:
   # msg: "{{ operate_results.stdout_lines }}"

- debug:
    msg: "{{ item }}"
  with_items: "{{ operate_results.stdout_lines }}"

######################################################################################################################################################################################################################################################################################
# Read SnapshotNames from the csv report
######################################################################################################################################################################################################################################################################################
#- name: Read SnapshotNames from CSV file and return a dictionary
  #read_csv:
    #path: "{{ operate_results.stdout_lines[0] }}"
    #delimiter: ','
  #register: names
#- debug:
    #msg: "{{ lookup('csvfile', '{{ item }}', col) }}"
  #with_items: "{{ operate_results.stdout_lines[0] }}"
######################################################################################################################################################################################################################################################################################
# Read SnapshotNames from "{{ operate_results.stdout_lines }}" to delete
######################################################################################################################################################################################################################################################################################
- name: Read SnapshotNames from "{{ operate_results.stdout_lines }}" to delete
  shell: az snapshot show --name "{{ item }}"
  with_items: "{{ operate_results.stdout_lines }}"

- debug: 
    msg: "{{ delete_result.stdout }}"

