---
######################################################################################################################################################################################################################################################################################
# Create file to store snapshot details fetched from shell script
###################################################################################################################################################################################################################################################################################### 
- name: Create a file to store the Snapshot List json output
  copy:
    dest: "/home/ansible/Azure_Old_Snapshot_List{{ '%Y-%m-%d%H:%M:%S' | strftime(ansible_date_time.epoch) }}.json"
    content: ""
    owner: ansible
    group: ansible
    mode: '0644'
  register: raw_report
- debug:
    msg: "{{ raw_report['dest'] }}"