---
#- name: Describe the snapshots and get the snapshot start time
  #command: aws ec2 describe-snapshots --region "{{ region }}" --query Snapshots[?(StartTime>="'$(date --date="'-1 month'" "'+%Y-%m-%d'")'")].[SnapshotId]
  #--filters Name=tag:snapshot,Values=yes --output text
  #register: command_output

#- debug: 
 #   msg: "{{command_output.stdout_lines}}"

- name: Ensure required tags are present on snapshots
  command: aws ec2 describe-snapshots --region "{{ region }}" --query "Snapshots[?!not_null(Tags[?Key == 'Expiry'].Value) && !not_null(Tags[?Key == 'Email'].Value)].[SnapshotId, OwnerId]" --output text
  
  register: ensured_snapshot_details

- debug:
    msg: "{{ item }}"
  with_items: "{{ensured_snapshot_details.stdout_lines}}"
  