---
#- name: Describe the snapshots and get the snapshot start time
  #command: aws ec2 describe-snapshots --region "{{ region }}" --query Snapshots[?(StartTime>="'$(date --date="'-1 month'" "'+%Y-%m-%d'")'")].[SnapshotId]
  #--filters Name=tag:snapshot,Values=yes --output text
  #register: command_output

#- debug: 
 #   msg: "{{command_output.stdout_lines}}"
######################################################################################################################################################################################################################################################################################
# FINDING UNTAGGED SNAPSHOTS 
###################################################################################################################################################################################################################################################################################### 
- name: Ensure required tags are present on snapshots
  command: aws ec2 describe-snapshots --region "{{ region }}" --owner-ids self --query "Snapshots[?!not_null(Tags[?Key == 'Expiry'].Value) && !not_null(Tags[?Key == 'Email'].Value)].{"'SnapShotID:'"SnapshotId, "'OwnerID:'"OwnerId, "'Tags:'"Tags}" --output text
  register: ensured_snapshot_details
- debug: msg="{{ensured_snapshot_details.stdout_lines}}"

######################################################################################################################################################################################################################################################################################
# VERIFYING THE SOURCE AND DESTINITION EMAIL IDs IN AWS SES
######################################################################################################################################################################################################################################################################################

- name: Ensure the SES Recipient Identity
  aws_ses_identity:
    region: "{{ region }}"
    identity: "{{ reciever_identity }}"
    state: present
  register: reciever

- debug: msg="{{reciever}}"

- name: Ensure the SES Sender Identity
  aws_ses_identity:
    region: "{{ region }}"
    identity: "{{ sender_identity }}"
    state: present
  register: sender

- debug: msg="{{sender}}"

######################################################################################################################################################################################################################################################################################
# SENDING THE EMAIL
######################################################################################################################################################################################################################################################################################

- name: Send the based on th conditions check
  when: sender.identity.exists == true and reciever.identity.exists == true
  shell: python files/ses.py {{ sender_identity }} {{ reciever_identity }} {{ region }}


#- debug:
 #   msg: "{{ item }}"
  #with_items: "{{ ensured_snapshot_details.stdout_lines }}"
