---
#- name: Describe the snapshots and get the snapshot start time
  #command: aws ec2 describe-snapshots --region "{{ region }}" --query Snapshots[?(StartTime>="'$(date --date="'-1 month'" "'+%Y-%m-%d'")'")].[SnapshotId]
  #--filters Name=tag:snapshot,Values=yes --output text
  #register: command_output

#- debug: 
 #   msg: "{{command_output.stdout_lines}}"

- name: Ensure required tags are present on snapshots
  command: aws ec2 describe-snapshots --region "{{ region }}" --owner-ids self --query "Snapshots[?!not_null(Tags[?Key == 'Expiry'].Value) && !not_null(Tags[?Key == 'Email'].Value)].{"'SnapShotID:'"SnapshotId, "'OwnerID:'"OwnerId, "'Tags:'"Tags}" --output text
  register: ensured_snapshot_details
- debug: msg="{{ensured_snapshot_details.stdout_lines}}"

- name: Ensure the SES Recipient Identity
  aws_ses_identity:
    identity: gcptesting4534@gmail.com
    state: present
  register: ensure_recipient_id

- debug: msg="{{ ensure_recipient_id.stdout_lines }}"

- name: Ensure the SES Sender Identity
  aws_ses_identity:
    identity: patiladi3110@gmail.com
    state: present
  register: ensure_sender_id

- debug: msg="{{ ensure_sender_id.stdout_lines }}"



#- debug:
 #   msg: "{{ item }}"
  #with_items: "{{ ensured_snapshot_details.stdout_lines }}"
  