---
#- name: Describe the snapshots and get the snapshot start time
 # command: aws ec2 describe-snapshots  --query Snapshots[?(StartTime<="'$(date --date='-1 month' '+%Y-%m-%d')'")].[SnapshotId]
  #--filters Name=tag:snapshot,Values=yes --output text
  #register: command_output
#- debug: msg="{{command_output.stdout_lines}}"

#- debug: 
 #   msg: "{{ item }}"
  #with_items: "{{ command_output.stdout_lines }}" 
- ec2_snapshot_info:
  region: "{{ aws_region }}"
