---
#- name: Describe the snapshots and get the snapshot start time
  #command: aws ec2 describe-snapshots --region "{{ region }}" --query Snapshots[?(StartTime>="'$(date --date="'-1 month'" "'+%Y-%m-%d'")'")].[SnapshotId]
  #--filters Name=tag:snapshot,Values=yes --output text
  #register: command_output

#- debug: 
 #   msg: "{{command_output.stdout_lines}}"

- name: Ensure all snapshots are tagged
  ec2_tag:
    region:  us-west-2
    resource: '{{ item.id }}'
    state: present
    tags:
      Expiry: Month
  loop: '{{ ec2_snapshot.snapshot_id }}'