---
- name: Get the volume IDs on the basis of tags and create their respective snapshots
  command: aws ec2 describe-volumes --region "{{ region }}" --query Volumes[*].[VolumeId] --filters Name=tag:snapshot,Values=yes --output json
  register: command_output
- debug: msg="{{command_output.stdout_lines}}"

- ec2_snapshot:
    volume_id: "{{ command_output.stdout_lines | list}}"
    region: "{{ region }}"
    description: Taking snapshot for the respected volumes 
  register: snapshot_output
- debug: msg="{{ snapshot_output.stdout }}"