- name: Apply READ-ONLY policy to new groups that have been recently created
  iam_policy:
    iam_type: group
    iam_name: "{{ item.created_group.group_name }}"
    policy_name: "READ-ONLY"
    policy_document: files/Full_ReadList_Limited_WriteTagging.json
    state: present
  loop: "{{ new_groups.results }}"