---
- name: Create a user and attach a policy to it
  iam:
     iam_type: user
     name: "{{ item.user }}"
     password: "Admin@123"
     access_key_state: create
     state: present
  with_items: 
     - { user: "{{ username }}" }
  register: "username"
- name: Attach policy to created user
  iam_policy:
      iam_type: user
      iam_name: "{{ username }}"
      policy_name: "TestPolicy"
      policy_document: files/TestPolicy.json
      state: present
  register: 