# Advanced example, create two new groups and add a READ-ONLY policy to both
# groups.
- name: Create IAM Groups (Using extra variables from Job_Template)
  iam:
    iam_type: group
    name: "{{ item.name }}"
    state: present
  #loop:
   #  - Mario
    # - Luigi
  #register: new_groups
  with_items:
     #- { name: "Mario, Luigi, Group1, Group2" }
     - { name: "{{ group_names }}" }

  #register: group_names

- name: Apply (Full_ReadList_Limited_WriteTagging) policy to new groups that have been recently created
  iam_policy:
    iam_type: group
    iam_name: "{{ item.created_group.group_names }}"
    policy_name: "READ-ONLY"
    policy_document: files/Full_ReadList_Limited_WriteTagging.json
    state: present
  loop: "{{ group_names.results }}"