---
- name: "Create Two Groups, Mario and Luigi"
  iam:
    iam_type: user
    name: "{{ item.user }}"
    state: present
  #register: "{{ user }}"
  with_items: 
    - { user: "{{ username }}" }

- name: Apply READONLY policy to new groups that have been recently created
  iam_policy:
    iam_type: user
    iam_name: "{{ item.user }}"
    policy_name: "TEST-POLICY"
    policy_document: files/TestPolicy.json
    state: present
  #loop: "{{ item.user.results }}"