---
- name: Create an iam user
  iam:
     iam_type: user
     name: "{{ item.user }}"
     password: "Admin@123"
     access_key_state: create
     state: present
  register: username
- name: Apply policy to the created user
  iam_policy:
      iam_type: user
      iam_name: "{{ username }}"
      policy_name: "TestPolicy"
      policy_document: files/TestPolicy.json
      state: present
  #with_items: 
    # - { user: "{{ username }}" }