#Test
- name: Create IAM Groups 
  iam:
    iam_type: group
    iam_name: "{{ item.name }}"
    state: present
    #loop:
    #  - Mario
    # - Luigi
    register: group_name
  
  debug:
    msg: "The group is: {{ group_name }} "  
  with_items:
    - { name: "{{ group_name }}" }
    #- { name: "Mario, Luigi, Group1, Group2" }
    #register: group_name
  

- name: Apply (Full_ReadList_Limited_WriteTagging) policy to new groups that have been recently created
  iam_policy:
    iam_type: group
    iam_name: "{{ group_name }}"
    #iam_name: "{{ item.created_group.group_names }}"
    policy_name: "LimitedAccess"
    policy_document: files/Full_ReadList_Limited_WriteTagging.json
    state: present

    #register: group_name
  debug:
    msg: "The group is: {{ group_name }} "
  loop: "{{ group_name.stdout }}"    
    #loop: "{{ group_name.result }}"