# Advanced example, create two new groups and add a READ-ONLY policy to both groups.
- name: Create IAM Groups 
  iam:
    iam_type: group
    name: "{{ item.name }}"
    state: present
  #loop:
   #  - Mario
    # - Luigi
  register: group_name
  
  debug:
    msg: "The group is: {{ item }} "  
  with_items:
    - { name: "{{ group_name }}" }
     #- { name: "Mario, Luigi, Group1, Group2" }
     #register: group_name
  

- name: Apply (Full_ReadList_Limited_WriteTagging) policy to new groups that have been recently created
  iam_policy:
    iam_type: group
    iam_name: "{{ item.group_name }}"
    #iam_name: "{{ item.created_group.group_names }}"
    policy_name: "LimitedAccess"
    policy_document: files/Full_ReadList_Limited_WriteTagging.json
    state: present

    register: group_name
    debug:
      msg: "The group is: {{ item }} "
    loop: "{{ group_name.stdout }}"    
    #loop: "{{ group_name.result }}"