---
- name: "Create Two Groups, Mario and Luigi"
  iam:
    iam_type: user
    name: "{{ item.user }}"
    state: present
  with_items: 
    - { user: "{{ username }}" }

  register: "{{ user }}"

#- name: Apply READONLY policy to new groups that have been recently created
 # iam_policy:
  #  iam_type: group
   # iam_name: "{{ item.created_group }}"
    #policy_name: "READ-ONLY"
    #policy_document: readonlypolicy.json
    #state: present
  #loop: "{{ created_group.results }}"