---
######################################################################################################################################################################################################################################################################################
# FINDING UNTAGGED SNAPSHOTS 
###################################################################################################################################################################################################################################################################################### 
- name: List out Untagged snapshots in a subscription
  shell: az snapshot  list --query "[?not_null(tags.Expiry != '')].[name, resourceGroup, timeCreated, sku.tier, location, id]" -o tsv | sed -e 's/\t/,/g'
  register: ensured_snapshot_details
- debug: msg="{{ ensured_snapshot_details.stdout_lines }}"

- debug:
    msg: "{{ item }}"
  with_items: "{{ ensured_snapshot_details.stdout_lines }}"

######################################################################################################################################################################################################################################################################################
# Storing Details to json File 
###################################################################################################################################################################################################################################################################################### 

- name: Create a file to store the Untagged Snapshot Report
  copy:
    dest: "/home/ansible/AZUREUntaggedSnapshotReport{{ '%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch) }}.csv"
    content: "{{ item }}"
    owner: ansible
    group: ansible
    mode: '0644'
  register: raw_report
  with_items: "{{ ensured_snapshot_details.stdout_lines | join('\n') }}"
- debug:
    msg: "{{ raw_report['results'][0]['dest'] }}"
    #['results'][0]['dest']

######################################################################################################################################################################################################################################################################################
# Adding Column Name to the Report
######################################################################################################################################################################################################################################################################################
- name: Add the headers as column names
  script: files/Push_Headers.py "{{ raw_report['results'][0]['dest'] }}"

