---
######################################################################################################################################################################################################################################################################################
# FINDING OLDER SNAPSHOTS
###################################################################################################################################################################################################################################################################################### 
#- name: Describe the snapshots and get the snapshot start time
 # command: aws ec2 describe-snapshots --region "{{ region }}" --query Snapshots[?(StartTime>="'$(date --date="'-1 month'" "'+%Y-%m-%d'")'")].[SnapshotId]
  #--filters Name=tag:snapshot,Values=yes --output text
  #register: command_output

#- debug: 
 #   msg: "{{command_output.stdout_lines}}"

 ######################################################################################################################################################################################################################################################################################
# Calling delete_snapshot.py
######################################################################################################################################################################################################################################################################################

- name: Execute the Snapshot Deletion Program
  script: files/delete_snapshot.py
  register: created_file
- debug: 
    msg: "{{ item.[2] }}"
  loop: "{{ created_file.stdout_lines }}"